#!/usr/bin/env python
# -*- coding: utf-8 -*-
import numpy as np


def load_file(filename, calibration_dict=None):
    if filename.endswith('.csv'):
        data = load_etrike(filename)
        return convert_etrike(data, calibration_dict)
    elif filename.endswith('.h5'):
        data = load_cain(filename)
        return convert_cain(data)


def load_etrike(filename):
    # steer angle and speed are sampled as integer types but we later convert
    # them to floats for plotting
    return np.recfromcsv(filename, delimiter=',', dtype=np.float64)


def convert_etrike(record, calibration_dict):
    """ Convert record fields from sampled unit to SI unit using provided
        calibration_dict generated by calibrate.py.
        This function is idempotent as is uses the names of the record fields
        to determine if conversion should occur.

        Returns True if conversion is performed.
    """
    names = list(record.dtype.names)
    newnames = ['time']
    if names[0] == newnames[0]:
        return record

    for name in names[1:]:
        if name.startswith('acc'):
            newname = 'accelerometer ' + name[3]
        elif name.startswith('gyro'):
            newname = 'gyroscope ' + name[4]
        elif name == 'steerangle_lsb':
            newname = 'steer angle'
        elif name == 'speed_lsb':
            newname = 'speed'
        else:
            raise ValueError(
                'conversion for signal {} is not defined'.format(name))
        # conversion assumes linear relationship incorporates both calibration
        # and unit conversion
        record[name] = np.polyval(calibration_dict[newname],
                                  record[name])
        newnames.append(newname)

    record.dtype.names = newnames
    return record
